name: Build and Release

on: 
  push: 
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write # Required for creating Releases

jobs:
  build-mac:
    runs-on: macos-latest
    # project specific steps for building executable on macos

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with: 
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build Mac App
        run: ./gradlew clean build createMacApp

      - name: Upload Mac DMG
        uses: actions/upload-artifact@v4
        with: 
          name: mac-dmg
          path: app/build/distributions/mac/*.dmg
          retention-days: 1 
  
  build-windows:
    runs-on: windows-latest
    # project specific steps for building executable on macos
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with: 
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build Windows App
        run: ./gradlew clean build createWindowsApp

      - name: Upload Windows msi
        uses: actions/upload-artifact@v4
        with: 
          name: windows-msi
          path: app/build/distributions/windows/*.msi
          retention-days: 1
      
  create-release:
    needs: [build-mac, build-windows]
    runs-on: ubuntu-latest
    # further steps for uploading artifacts to Releases Tab

    steps:
      - name: Download Mac DMG
        uses: actions/download-artifact@v4
        with:
          name: mac-dmg
          path: ./artifacts/mac

      - name: Download Windows MSI
        uses: actions/download-artifact@v4
        with:
          name: windows-msi
          path: ./artifacts/windows

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/mac/*.dmg
            ./artifacts/windows/*.msi
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}